# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Biased_Cont_Labelling_Theory_c <- function(kappa, alpha, beta, Ns) {
    .Call('_CryptDriftR_Biased_Cont_Labelling_Theory_c', PACKAGE = 'CryptDriftR', kappa, alpha, beta, Ns)
}

LinearGillespie <- function(numSim, nu, a_mat, x0, time_vec) {
    .Call('_CryptDriftR_LinearGillespie', PACKAGE = 'CryptDriftR', numSim, nu, a_mat, x0, time_vec)
}

Crypt_drift <- function(alpha, beta, Ns, time_intervals, persisting, splitNum = 0L) {
    .Call('_CryptDriftR_Crypt_drift', PACKAGE = 'CryptDriftR', alpha, beta, Ns, time_intervals, persisting, splitNum)
}

Infer_Biased_mcmc <- function(x, time_intervals, max_iter, Ns_WT, lambda_WT, tau_fix) {
    .Call('_CryptDriftR_Infer_Biased_mcmc', PACKAGE = 'CryptDriftR', x, time_intervals, max_iter, Ns_WT, lambda_WT, tau_fix)
}

Infer_Biased_wLambda_mcmc <- function(x, time_intervals, max_iter, Ns_WT, tau_fix) {
    .Call('_CryptDriftR_Infer_Biased_wLambda_mcmc', PACKAGE = 'CryptDriftR', x, time_intervals, max_iter, Ns_WT, tau_fix)
}

Infer_Neutral_mcmc <- function(x, time_intervals, max_iter) {
    .Call('_CryptDriftR_Infer_Neutral_mcmc', PACKAGE = 'CryptDriftR', x, time_intervals, max_iter)
}

